// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {store} from '../models';

export function AddRepo(arg1:string):Promise<void>;

export function AddRepos(arg1:Array<string>):Promise<Array<string>>;

export function ChooseFolder(arg1:string):Promise<string>;

export function GetEnv():Promise<main.Env>;

export function GetRepo(arg1:string):Promise<main.RepoView>;

export function GetSettings():Promise<store.Settings>;

export function ListRepos():Promise<Array<main.RepoView>>;

export function OpenIn(arg1:string,arg2:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function RemoveRepo(arg1:string):Promise<void>;

export function Reorder(arg1:Array<string>):Promise<void>;

export function SaveSettings(arg1:store.Settings):Promise<void>;

export function ScanFolder(arg1:string,arg2:number):Promise<Array<main.ScanResult>>;

export function SetPinned(arg1:string,arg2:boolean):Promise<void>;
