// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRepo(arg1) {
  return window['go']['main']['App']['AddRepo'](arg1);
}

export function AddRepos(arg1) {
  return window['go']['main']['App']['AddRepos'](arg1);
}

export function AddWorktree(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddWorktree'](arg1, arg2, arg3, arg4);
}

export function CheckGitHub() {
  return window['go']['main']['App']['CheckGitHub']();
}

export function ChooseFolder(arg1) {
  return window['go']['main']['App']['ChooseFolder'](arg1);
}

export function CommitChanges(arg1, arg2, arg3) {
  return window['go']['main']['App']['CommitChanges'](arg1, arg2, arg3);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function CreateBranch(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateBranch'](arg1, arg2, arg3);
}

export function DeleteBranch(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteBranch'](arg1, arg2, arg3);
}

export function DiscardFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['DiscardFiles'](arg1, arg2, arg3);
}

export function EnterMini() {
  return window['go']['main']['App']['EnterMini']();
}

export function ExitMini() {
  return window['go']['main']['App']['ExitMini']();
}

export function GetAutostart() {
  return window['go']['main']['App']['GetAutostart']();
}

export function GetCommitDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCommitDiff'](arg1, arg2, arg3);
}

export function GetDetail(arg1) {
  return window['go']['main']['App']['GetDetail'](arg1);
}

export function GetDiff(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetDiff'](arg1, arg2, arg3, arg4);
}

export function GetEnv() {
  return window['go']['main']['App']['GetEnv']();
}

export function GetLog(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetLog'](arg1, arg2, arg3);
}

export function GetRepo(arg1) {
  return window['go']['main']['App']['GetRepo'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function IsMini() {
  return window['go']['main']['App']['IsMini']();
}

export function ListBranches(arg1) {
  return window['go']['main']['App']['ListBranches'](arg1);
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function ListRepos() {
  return window['go']['main']['App']['ListRepos']();
}

export function ListWorktrees(arg1) {
  return window['go']['main']['App']['ListWorktrees'](arg1);
}

export function OpenIn(arg1, arg2) {
  return window['go']['main']['App']['OpenIn'](arg1, arg2);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RemoveRepo(arg1) {
  return window['go']['main']['App']['RemoveRepo'](arg1);
}

export function RemoveWorktree(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveWorktree'](arg1, arg2, arg3);
}

export function Reorder(arg1) {
  return window['go']['main']['App']['Reorder'](arg1);
}

export function RunOp(arg1, arg2) {
  return window['go']['main']['App']['RunOp'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanFolder(arg1, arg2) {
  return window['go']['main']['App']['ScanFolder'](arg1, arg2);
}

export function SetAutostart(arg1) {
  return window['go']['main']['App']['SetAutostart'](arg1);
}

export function SetGroup(arg1, arg2) {
  return window['go']['main']['App']['SetGroup'](arg1, arg2);
}

export function SetPinned(arg1, arg2) {
  return window['go']['main']['App']['SetPinned'](arg1, arg2);
}

export function ShowCommit(arg1, arg2) {
  return window['go']['main']['App']['ShowCommit'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StageFiles(arg1, arg2) {
  return window['go']['main']['App']['StageFiles'](arg1, arg2);
}

export function StashAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['StashAction'](arg1, arg2, arg3);
}

export function StashPush(arg1, arg2, arg3) {
  return window['go']['main']['App']['StashPush'](arg1, arg2, arg3);
}

export function SwitchBranch(arg1, arg2, arg3) {
  return window['go']['main']['App']['SwitchBranch'](arg1, arg2, arg3);
}

export function ToggleMiniPanel() {
  return window['go']['main']['App']['ToggleMiniPanel']();
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}

export function UndoLastCommit(arg1) {
  return window['go']['main']['App']['UndoLastCommit'](arg1);
}

export function UnstageFiles(arg1, arg2) {
  return window['go']['main']['App']['UnstageFiles'](arg1, arg2);
}
