// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gitx} from '../models';
import {github} from '../models';
import {main} from '../models';
import {store} from '../models';

export function AddRepo(arg1:string):Promise<void>;

export function AddRepos(arg1:Array<string>):Promise<Array<string>>;

export function AddWorktree(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<gitx.OpResult>;

export function CheckGitHub():Promise<github.Health>;

export function ChooseFolder(arg1:string):Promise<string>;

export function CommitChanges(arg1:string,arg2:string,arg3:boolean):Promise<gitx.OpResult>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function CreateBranch(arg1:string,arg2:string,arg3:string):Promise<gitx.OpResult>;

export function DeleteBranch(arg1:string,arg2:string,arg3:boolean):Promise<gitx.OpResult>;

export function DiscardFiles(arg1:string,arg2:Array<string>,arg3:boolean):Promise<gitx.OpResult>;

export function GetAutostart():Promise<boolean>;

export function GetCommitDiff(arg1:string,arg2:string,arg3:string):Promise<gitx.Diff>;

export function GetDetail(arg1:string):Promise<main.RepoDetail>;

export function GetDiff(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<gitx.Diff>;

export function GetEnv():Promise<main.Env>;

export function GetLog(arg1:string,arg2:number,arg3:number):Promise<Array<gitx.Commit>>;

export function GetRepo(arg1:string):Promise<main.RepoView>;

export function GetSettings():Promise<store.Settings>;

export function HideWindow():Promise<void>;

export function ListBranches(arg1:string):Promise<Array<gitx.Branch>>;

export function ListGroups():Promise<Array<string>>;

export function ListRepos():Promise<Array<main.RepoView>>;

export function ListWorktrees(arg1:string):Promise<Array<gitx.Worktree>>;

export function OpenIn(arg1:string,arg2:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function QuitApp():Promise<void>;

export function RemoveRepo(arg1:string):Promise<void>;

export function RemoveWorktree(arg1:string,arg2:string,arg3:boolean):Promise<gitx.OpResult>;

export function Reorder(arg1:Array<string>):Promise<void>;

export function RunOp(arg1:string,arg2:string):Promise<Array<gitx.OpResult>>;

export function SaveSettings(arg1:store.Settings):Promise<void>;

export function ScanFolder(arg1:string,arg2:number):Promise<Array<main.ScanResult>>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function SetGroup(arg1:string,arg2:string):Promise<void>;

export function SetPinned(arg1:string,arg2:boolean):Promise<void>;

export function ShowCommit(arg1:string,arg2:string):Promise<gitx.CommitDetail>;

export function ShowWindow():Promise<void>;

export function StageFiles(arg1:string,arg2:Array<string>):Promise<gitx.OpResult>;

export function StashAction(arg1:string,arg2:string,arg3:string):Promise<gitx.OpResult>;

export function StashPush(arg1:string,arg2:string,arg3:boolean):Promise<gitx.OpResult>;

export function SwitchBranch(arg1:string,arg2:string,arg3:boolean):Promise<gitx.OpResult>;

export function ToggleWindow():Promise<void>;

export function UndoLastCommit(arg1:string):Promise<gitx.OpResult>;

export function UnstageFiles(arg1:string,arg2:Array<string>):Promise<gitx.OpResult>;
