// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRepo(arg1) {
  return window['go']['main']['App']['AddRepo'](arg1);
}

export function AddRepos(arg1) {
  return window['go']['main']['App']['AddRepos'](arg1);
}

export function CheckGitHub() {
  return window['go']['main']['App']['CheckGitHub']();
}

export function ChooseFolder(arg1) {
  return window['go']['main']['App']['ChooseFolder'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function GetEnv() {
  return window['go']['main']['App']['GetEnv']();
}

export function GetRepo(arg1) {
  return window['go']['main']['App']['GetRepo'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function ListRepos() {
  return window['go']['main']['App']['ListRepos']();
}

export function OpenIn(arg1, arg2) {
  return window['go']['main']['App']['OpenIn'](arg1, arg2);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RemoveRepo(arg1) {
  return window['go']['main']['App']['RemoveRepo'](arg1);
}

export function Reorder(arg1) {
  return window['go']['main']['App']['Reorder'](arg1);
}

export function RunOp(arg1, arg2) {
  return window['go']['main']['App']['RunOp'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanFolder(arg1, arg2) {
  return window['go']['main']['App']['ScanFolder'](arg1, arg2);
}

export function SetGroup(arg1, arg2) {
  return window['go']['main']['App']['SetGroup'](arg1, arg2);
}

export function SetPinned(arg1, arg2) {
  return window['go']['main']['App']['SetPinned'](arg1, arg2);
}
